Name = input("Please Enter your Name : ")
Location = input("Location : ")
mobile_num= input("Please Enter the Mobile number : ")
email_id = input("please Enter Email ID : ")
password = input('Please Enter the password : ')
print(Name)
print(Location)
print("Mob num:"+mobile_num)
print(email_id)
print("password:"+password)
print(Name + " is the king of " + Location)